name: Build, Test and Deploy

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  version-check:
    uses: kokoichi206/utils/.github/workflows/version-check.yml@main

  build:
    # HEADコミットが'skip ci'を含んでいれば、ciをキャンセルする。
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    uses: kokoichi206/utils/.github/workflows/build.yml@main

  lint:
    uses: kokoichi206/utils/.github/workflows/ktlint.yml@main

  local-test:
    needs: [ version-check, build, lint ]
    uses: kokoichi206/utils/.github/workflows/local-test.yml@main

  android-emulator-test:
    needs: [ version-check, build, lint ]
    uses: kokoichi206/utils/.github/workflows/emulator-test.yml@main

  deploy:
    needs: [ build, local-test, android-emulator-test ]
    uses: kokoichi206/utils/.github/workflows/deploy.yml@main
    secrets:
      ENCODED_RELEASE_KEYSTORE: ${{ secrets.ENCODED_RELEASE_KEYSTORE }}
      RELEASE_KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
      RELEASE_KEYSTORE_KEY_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}

  create-release:
    needs: [ build, local-test, android-emulator-test ]
    uses: kokoichi206/utils/.github/workflows/create-release.yml@main

  license-checker:
    needs: [ build, local-test, android-emulator-test ]
    uses: kokoichi206/utils/.github/workflows/license.yml@main  

  create-kdoc:
    needs: [ build, local-test, android-emulator-test ]
    uses: kokoichi206/utils/.github/workflows/kdoc.yml@main

  update-docs:
    runs-on: ubuntu-20.04
    needs: [ license-checker, create-kdoc ]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Restore cache for upload license results
        uses: actions/cache@v2
        with:
          path: |
            ./public
          key: ${{ runner.os }}-public-${{ hashFiles('./app/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-public-
      - name: Restore cache for upload kdoc results
        uses: actions/cache@v2
        with:
          path: |
            ./kdoc
          key: ${{ runner.os }}-kdoc-${{ hashFiles('./app/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-kdoc-
      - name: Move kdoc to public dir
        run: |
          if [ -d public/kdoc ]; then
            rm -rf public/kdoc
          fi
          mv kdoc public
      - name: Move index to public dir
        run: |
          if [ -e public/index.html ]; then
            rm public/index.html
          fi
          mv docs/pages/index.html public
      # Update gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # メインブランチへの更新かつ、差分がある場合
        # if: ${{ (github.ref == 'refs/heads/main') && (needs.license-checker.outputs.is_idff == 'true') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      # FIXME: 以下の２つはうまく output を分岐させて、１つの step で書きたい
      - name: Outputs when diff found
        uses: actions/github-script@v5
        # PR かつ、差分がある場合
        if: ${{ (github.event_name == 'pull_request') && (needs.license-checker.outputs.is_idff == 'true') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### CI/CD Results
            Hello, I'm kokoichi 👋
            License diff found in your commit!
            Please check if there's no problem.
            <details><summary>Diff metadata</summary>
            \`\`\`\n
            ${{ steps.diff-metadata.outputs.diff }}
            \`\`\
            </details>
            <details><summary>Diff Licenses</summary>
            \`\`\`\n
            ${{ steps.diff-license.outputs.diff }}
            \`\`\
            </details>
            
            see more xxx
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Outputs when NO diff found
        uses: actions/github-script@v5
        # PR かつ、差分がない場合
        if: ${{ (github.event_name == 'pull_request') && (needs.license-checker.outputs.is_idff == 'false') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### CI/CD Results
            Hello, I'm kokoichi 👋
            No License Diff Found
            see current license here;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      # artifact にも保存しておく
      - name: Upload license related files
        uses: actions/upload-artifact@v2
        with:
          name: license
          path: ./public
          if-no-files-found: error
          retention-days: 3
