name: Build, Test and Deploy

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  version-check:
    uses: kokoichi206/utils/.github/workflows/android-version-check.yml@main

  build:
    # HEADコミットが'skip ci'を含んでいれば、ciをキャンセルする。
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    uses: kokoichi206/utils/.github/workflows/android-build.yml@main

  lint:
    uses: kokoichi206/utils/.github/workflows/android-ktlint.yml@main

  local-test:
    needs: [ version-check, build, lint ]
    uses: kokoichi206/utils/.github/workflows/android-local-test.yml@main

  android-emulator-test:
    needs: [ version-check, build, lint ]
    uses: kokoichi206/utils/.github/workflows/android-emulator-test.yml@main

  deploy:
    needs: [ build, local-test, android-emulator-test ]
    uses: kokoichi206/utils/.github/workflows/android-deploy.yml@main
    secrets:
      ENCODED_RELEASE_KEYSTORE: ${{ secrets.ENCODED_RELEASE_KEYSTORE }}
      RELEASE_KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
      RELEASE_KEYSTORE_KEY_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}

  create-release:
    needs: [ build, local-test, android-emulator-test ]
    uses: kokoichi206/utils/.github/workflows/android-create-release.yml@main

  license-checker:
    needs: [ build, local-test, android-emulator-test ]
    uses: kokoichi206/utils/.github/workflows/android-license.yml@main  
