name: Run tests every day

on:
  schedule:
    # 日本時間24時00分
    - cron: '0 15 * * *'

jobs:
  build:
    uses: kokoichi206/utils/.github/workflows/android-build.yml@main

  local-test:
    needs: [ build ]
    uses: kokoichi206/utils/.github/workflows/android-local-test.yml@main

  android-emulator-test:
    needs: [ build ]
    uses: kokoichi206/utils/.github/workflows/android-emulator-test.yml@main
