name: Main

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  schedule:
    # 日本時間24時00分
    - cron: '0 15 * * *'

jobs:
  lint:
    uses: kokoichi206/utils/.github/workflows/ios-lint.yml@main

  build-check:
    needs: [lint]
    uses: kokoichi206/utils/.github/workflows/ios-build.yml@main

  test:
    needs: [lint]
    uses: kokoichi206/utils/.github/workflows/ios-test.yml@main
