name: Emulator test

on:
  workflow_call:

jobs:
  android-emulator-test:
    runs-on: macos-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        api-level: [ 26, 29, 30 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # JDKのセットアップ
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Restore cache for Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # api-levelによってエミュレータのターゲットを変える。
      # https://docs.github.com/ja/actions/learn-github-actions/workflow-commands-for-github-actions#example
      - name: Set the emulator target name to GITHUB_ENV 
        id: setup_target_name
        run: |
          # target="default"
          target="google_apis"
          if [ "${{ matrix.api-level }}" -ge "29" ]; then
            target="google_apis"
          fi
          echo "env_target=$target" >> $GITHUB_ENV
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ env.env_target }}
          arch: x86
          profile: Galaxy Nexus
          script: ./gradlew connectedCheck --stacktrace

      # テスト結果をアップロードする。
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Android-Test-Reports-API${{ matrix.api-level }}
          path: app/build/reports
        if: always()
