name: Local test

on:
  workflow_call:
    secrets:
      ENCODED_RELEASE_KEYSTORE:
        required: true
      RELEASE_KEYSTORE_STORE_PASSWORD:
        required: true
      RELEASE_KEYSTORE_KEY_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    environment: production
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # release.keystoreをデコードする。
      - name: Decode Keystore
        run: echo ${{ secrets.ENCODED_RELEASE_KEYSTORE }} | base64 --decode > ./app/release.keystore

      # aab形式でビルドする。
      - name: Build AAB
        run: ./gradlew :app:bundleRelease
        env:
          RELEASE_KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
          RELEASE_KEYSTORE_KEY_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}

      - name: Upload aab file
        uses: actions/upload-artifact@v2
        with:
          name: aab
          path: app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: error
          retention-days: 3
