name: Build

on:
  workflow_call:

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get scheme of BASE_REF
        id: return-scheme-name
        run: |
          PATH_TO_PBX="$(find . -name project.pbxproj)"
          ARR=(${PATH_TO_PBX//./ })
          echo "::set-output name=name::$(echo ${ARR[0]:1})"

      - name: Run tests
        run: xcodebuild
            -scheme ${{ steps.return-scheme-name.outputs.name }}
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11 Pro'
            clean test

      - name: Store cache for uploading
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/*/Logs/Test
          key: ${{ runner.os }}-tests-${{ hashFiles('$(find . -name project.pbxproj)') }}
          restore-keys: |
            ${{ runner.os }}-tests-
