name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version of BASE_REF
        id: return-scheme-name
        run: |
          PATH_TO_PBX="$(find . -name project.pbxproj)"
          ARR=(${PATH_TO_PBX//./ })
          echo "::set-output name=name::$(echo ${ARR[0]:1})"

      - name: Build
        run: xcodebuild
            -scheme ${{ steps.return-scheme-name.outputs.name }}
            -sdk iphonesimulator
            -configuration Debug
            build

      - name: Store cache for later uploading
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/*/Logs/Build/*
            ~/Library/Developer/Xcode/DerivedData/*/Build/Products
          key: ${{ runner.os }}-build-${{ hashFiles('$(find . -name project.pbxproj)') }}
          restore-keys: |
            ${{ runner.os }}-build-
